#!/bin/bash

# Small script to get information from `headsetcontrol` to `polybar`.
OPTION_BATTERY='-b'
OPTION_SILENT='-o ENV'
SEARCH_HEADSETCONTROL="headsetcontrol"
HEADSETCONTROL=""

errcho(){ echo "$@" 1>&2; }


# Try to detect headsetcontrol in $PATH
if command -v "$SEARCH_HEADSETCONTROL" > /dev/null ; then
    HEADSETCONTROL="$(command -v $SEARCH_HEADSETCONTROL )"
fi

if [ -z "$HEADSETCONTROL" ]; then
    echo "$SEARCH_HEADSETCONTROL not found in PATH"
    errcho "Exiting.."
    exit 1
fi

# Make sure something is detected
DEVICE="$($HEADSETCONTROL 2> /dev/null | grep 'Found' )"
if [ -z "$DEVICE" ]; then
    echo "ﳌ Disconnected"
    #errcho "Exiting.."
    #exit 1
fi

if [ $(echo "$DEVICE" | wc -l ) -eq 2 ]; then
    echo " Too many devices!"
    errcho "$DEVICES"
    errcho "Exiting.."
    exit 1
fi

# Select Device Name and find Status
DEVICE="$(echo $DEVICE | cut -d' ' -f2-)"
DEVICE="${DEVICE%!}" # remove exclamation mark


get_battery() {
    $HEADSETCONTROL $OPTION_BATTERY $OPTION_SILENT | grep DEVICE_0_BATTERY_LEVEL | awk -F= '{print $2}'
}

get_status() {
	battery="$($HEADSETCONTROL $OPTION_BATTERY $OPTION_SILENT 2> /dev/null)"
    if [ -n "$battery" ]; then
        # echo 'connected'
        echo ''
        #return 0
    else
        # echo 'disconnected'
        echo 'ﳌ'
        #return 1
    fi
}

get_status_message() {
	battery="$($HEADSETCONTROL $OPTION_BATTERY $OPTION_SILENT 2> /dev/null)"
    if [ -n "$battery" ]; then
        echo 'connected'
        #echo ''
        #return 0
    else
        echo 'disconnected'
        #echo 'ﳌ'
        #return 1
    fi
}



# Bail if it is not connected
if ! get_status > /dev/null; then
    echo "$(get_status) ${DEVICE}: (disconnected)"
    # errcho "Exiting.."
    # exit 1
fi
# Polybar output

case "$1" in
    device)
        echo $DEVICE is $(get_status)
        ;;
    battery)
        echo $(get_battery)%
        ;;
    status|*)
        #echo "$(get_status) $DEVICE: $(get_battery)%"
        status="$(get_status_message)"
        if [[ "$status" == *"disconnected"* ]]; then
            echo "$(get_status) ${DEVICE}: (powered off)"
        else
            if [[ "$(get_battery)" = -1 ]]; then
                echo "$(get_status) $DEVICE: Charging"
            else
                echo "$(get_status) $DEVICE: $(get_battery)%"
            fi
        fi
        ;;
esac
